---
javascripts:
- base:
  - powerposm/jquery-1.4.4.min
  - powerposm/jquery-ui-1.8.7.custom.min
  - powerposm/jquery.progressbar.min
  - powerposm/application
stylesheets:
- base:
  - powerposm/admin
  - powerposm/ui-lightness/jquery-ui-1.8.7.custom